# Generated by Django 5.0.6 on 2024-05-21 09:19

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('league_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='League Logo')),
            ],
            options={
                'verbose_name_plural': 'League',
            },
        ),
        migrations.CreateModel(
            name='Player_bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nationality', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=200)),
                ('player_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Player Image')),
                ('league_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.league')),
            ],
            options={
                'verbose_name_plural': 'Athlete_bio',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.league')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
