# Generated by Django 5.0.6 on 2024-05-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_bio',
            new_name='Player',
        ),
    ]
